// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

type UserTable struct {
	UserID    int32   `json:"user_id"`
	Username  *string `json:"username"`
	PublicKey string  `json:"public_key"`
}
