// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: user_queries.sql

package sqlc

import (
	"context"
)

const getPublicKey = `-- name: GetPublicKey :one
SELECT public_key
FROM user_table 
WHERE username = $1
`

func (q *Queries) GetPublicKey(ctx context.Context, username *string) (string, error) {
	row := q.db.QueryRow(ctx, getPublicKey, username)
	var public_key string
	err := row.Scan(&public_key)
	return public_key, err
}

const registerUser = `-- name: RegisterUser :exec
INSERT INTO user_table(username, public_key) 
VALUES ($1, $2)
`

type RegisterUserParams struct {
	Username  *string `json:"username"`
	PublicKey string  `json:"public_key"`
}

func (q *Queries) RegisterUser(ctx context.Context, arg RegisterUserParams) error {
	_, err := q.db.Exec(ctx, registerUser, arg.Username, arg.PublicKey)
	return err
}
